services:
  ms-security:
    # Build: usa el Dockerfile del directorio actual
    build:
      context: .
      dockerfile: Dockerfile

    # Nombre del contenedor interno
    container_name: ms-security-app
    ports:
      - "8083:8080"

    # Reiniciar siempre si falla
    restart: always

    # Variables de Entorno
    # NO pongas contraseñas reales aquí. Usa la sintaxis ${VAR}
    # y configura los valores reales en la pestaña "Environment" de Dokploy.
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      # Conexión DB
      - URL_BD_SECURITY=${URL_BD_SECURITY}
      - POSTGRES_USER=${USER_NAME_BD}
      - POSTGRES_PASSWORD=${PASSWORD_BD}
      - SCHEMA_NAME=${SCHEMA_NAME}
      # Seguridad Keycloak
      - ISSUER_URI_KEYCLOAK=${ISSUER_URI_KEYCLOAK}
      - JWK_SET_URI_KEYCLOAK=${ISSUER_URI_KEYCLOAK}

      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}

    # Configuración de red (opcional, pero buena práctica)
    networks:
      - siim-network

# Definimos la red
networks:
  siim-network:
    name: siim-global-net
    external: true