spring:
  application:
    name: ms-security
  datasource:
    url: ${URL_BD_SECURITY:jdbc:postgresql://192.168.0.18:5432/municipal_security?currentSchema=${SCHEMA_NAME}}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Abc12345}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${SCHEMA_NAME}
    liquibase-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${SCHEMA_NAME}
        format_sql: true
    show-sql: ${SHOW_SQL:true}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI_KEYCLOAK:http://localhost:8180/realms/tuxtepec-gob}
          jwk-set-uri: ${JWK_SET_URI_KEYCLOAK:http://keycloak:8180/realms/tuxtepec-gob/protocol/openid-connect/certs}

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web: INFO
      liquibase: INFO

app:
  security:
    client-id: ${KEYCLOAK_CLIENT_ID:siim-frontend}